Namespace DAoCServer
    Public Interface IPacketLib
        Sub ParsePlayerQuit(ByVal pPacket As DAOCPacket)
        Sub ParsePlayerModelChange(ByVal pPacket As DAOCPacket)
        Sub ParseRevive(ByVal pPacket As DAOCPacket)
        Sub ParseDead(ByVal pPacket As DAOCPacket)
        Sub ParseLocalPlayerSpeedUpdate(ByVal pPacket As DAOCPacket)
        Sub ParseObjectEquipment(ByVal pPacket As DAOCPacket)
        Sub ParseInventoryList(ByVal ppacket As DAOCPacket)
        Sub ParseGroupWindowUpdate(ByVal pPacket As DAOCPacket)
        Sub ParseGroupMembersUpdate(ByVal pPacket As DAOCPacket)
        Sub ParseVendorWindow(ByVal pPacket As DAOCPacket)
        Sub ParseLogUpdate(ByVal pPacket As DAOCPacket)
        Sub ParseProgressMeter(ByVal pPacket As DAOCPacket)
        Sub ParsePetWindowUpdate(ByVal pPacket As DAOCPacket)
        Sub ParsePetUpdate(ByVal pPacket As DAOCPacket)
        Sub ParseDialogueUpdate(ByVal pPacket As DAOCPacket)
        Sub ParseInterruptSpell(ByVal pPacket As DAOCPacket)
        Sub ParseSpellEffectAnimation(ByVal pPacket As DAOCPacket)
        Sub ParsePlayerCastSpell(ByVal pPacket As DAOCPacket)
        Sub ParseNewObject(ByVal pPacket As DAOCPacket, ByVal theClass As DAOCObjectClass)
        Sub ParseMobUpdate(ByVal pPacket As DAOCPacket)
        Sub ParseRemoveObject(ByVal pPacket As DAOCPacket)
        Sub ParsePlayerSpecsSpells(ByVal pPacket As DAOCPacket)
        Sub ParsePlayerSpecsSpellsAbils(ByVal pPacket As DAOCPacket)
        Sub ParsePlayerStatsUpdate(ByVal pPacket As DAOCPacket)
        Sub ParsePlayerDetails(ByVal pPacket As DAOCPacket)
        Sub ParseCharacterActivationRequest(ByVal pPacket As DAOCPacket)
        Sub ParseCharacterLoginInit(ByVal pPacket As DAOCPacket)
        Sub ParseAccountCharacters(ByVal pPacket As DAOCPacket)
        Sub ParseSetPlayerRegion(ByVal pPacket As DAOCPacket)
        Sub ParsePlayerUpdateHitPoints(ByVal pPacket As DAOCPacket)
        Sub ParsePlayerPosUpdate(ByVal pPacket As DAOCPacket)
        Sub ParsePlayerHeadUpdate(ByVal pPacket As DAOCPacket)
        Sub ParseLocalHealthUpdate(ByVal pPacket As DAOCPacket)
        Sub ParseAttackModeRequest(ByVal pPacket As DAOCPacket)
        Sub ParseSetGroundTarget(ByVal pPacket As DAOCPacket)
        Sub ParseLocalHeadUpdateFromClient(ByVal pPacket As DAOCPacket)
        Sub ParseSelectedIDUpdate(ByVal pPacket As DAOCPacket)
        Sub ParseLocalPosUpdateFromClient(ByVal pPacket As DAOCPacket)
        Sub ParsePlayerSkills(ByVal pPacket As DAOCPacket)
        Sub ParseLocalBuff(ByVal pPacket As DAOCPacket)
        Sub ParseConcentrationBuff(ByVal pPacket As DAOCPacket)
    End Interface
End Namespace

